version: '3.1'
services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - db
        env_file: .env
        volumes:
            - ./wp-content:/var/www/html/wp-content
    db:
        image: mysql:5.7
        restart: always
        env_file: .env
        volumes:
            - ./wp-db:/var/lib/mysql