version: '3.1'
services:
    wordpress:
        image: wordpress:4.9.7
        restart: always
        ports:
            - "8080:80"
        env_file: .env
        volumes:
            - ./docker_volumes/wp-content:/var/www/html/wp-content
    db:
        image: mysql:5.7
        restart: always
        env_file: .env
        volumes:
            - ./docker_volumes/wp-db:/var/lib/mysql